import { ErrorUtil } from '../../../middleware/ErrorUtil';
import User, { AuthType } from '../../auth/model/Auth';
import PlayerModel from '../../profiles/player/model/PlayerModel';
import { EmailService } from '../email/EmailService';
import Notification from '../model/Notification';

export default class UserEvents {
  public onPasswordUpdated = async (event: { userId: string; newPassword: string; isAutoGenerated: boolean }) => {
    const { userId, newPassword } = event;
    console.info(`[Notification] Password updated for user ID: ${userId}`);
    // Find the user by ID
    const user = await User.findById(userId);
    if (!user) {
      throw new ErrorUtil('User not found', 404);
    }
    const profile = await PlayerModel.findOne({ user: user._id as any }).lean();

    // Create a notification
    await Notification.insertNotification(
      user._id as any,
      null as any,
      'Password Updated',
      `Your password has been updated successfully.`,
      'user.passwordUpdated',
      user._id as any
    );

    if (event.isAutoGenerated) {
      await EmailService.sendEmail({
        to: user.email,
        subject: 'Your Password Has Been Updated',
        templateId: 'auto-pass-reset-tapestry',
        data: {
          name: profile?.displayName,
          signInUrl: `https://app.tapestry-rpg.com/`,
          supportEmail: 'support@tapestry-ttrpg.com',
          currentYear: new Date().getFullYear(),
          subject: 'Your Password Has Been Updated',
          password: newPassword,
        },
      });
    }
  };
}
